In [24]:
import numpy as np

data  = np.ones([2,4])

print(data)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
import numpy as np

data  = np.zeros([4,5])

print(data)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
import numpy as np

data = np.random.randint(1,5,4)

print(data)

[4 2 1 2]


In [11]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
})

print(df)

# only Name column
print(df["Name"])

  Name  Age  Marks
0    A   20     85
1    B   21     90
2    C   19     78
0    A
1    B
2    C
Name: Name, dtype: str


In [10]:
import numpy as np

x = np.array([[1,2,3,4],
             [5,6,7,8]])

y = np.array([[2,4,6,8],
             [10,12,14,16]])

print(x*y)


[[  2   8  18  32]
 [ 50  72  98 128]]


In [5]:
import numpy as np

data = np.arange(1,11)
new_data = data.reshape(2,5)
print(new_data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [1]:
import pandas as pd 

data = {
    "Number": [1, 2, 3, 4],
    "Table of 2": [2, 4, 6, 8]
}

dataframe = pd.DataFrame(data)

print(dataframe)


   Number  Table of 2
0       1           2
1       2           4
2       3           6
3       4           8
