In [12]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,-4,5,-6,7,-8,9])
print(np.mod(b,2))

[1 0 1 0 1 0 1 0 1]


In [10]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,-4,5,-6,7,-8,9])
print(np.abs(b))

[1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.square(a,b))

[ 1  4  9 16 25 36 49 64 81]


In [8]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.power(a,b))

[        1         4        27       256      3125     46656    823543
  16777216 387420489]


In [6]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.divide(a,b))

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.multiply(a,b))

[ 1  4  9 16 25 36 49 64 81]


In [4]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.subtract(a,b))

[0 0 0 0 0 0 0 0 0]


In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.add(a,b))

[ 2  4  6  8 10 12 14 16 18]


In [1]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
print(np.std(a))

2.581988897471611
