In [ ]:
import numpy as np

ar = np.array([1,2,3,4])

print(ar)

In [ ]:
import numpy as np
import time

n = 10

#lIST
list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result = [list1[i] + list2[i] for i in range (n)]
list_time = time.time() - start

# numpya arry


ar1 = np.arange(n, dtype=np.int32)
ar2 = np.arange(n, dtype=np.int32)

start2 = time.time()
result_arr = ar1 + ar2 
numpy_time = time.time() - start2

print(f'List Time   : {list_time:.6f} sec')
print(f'Numpy Time  : {numpy_time:.6f} sec')
print(f'Numpy is approximetly {list_time/numpy_time:.2f}x faster')

In [2]:
import numpy as np

ar = np.array([1,2,3,4])

print(ar.dtype)
print(ar.ndim)
print(ar.size)
print(ar.shape)

int64
1
4
(4,)


In [ ]:
import numpy as np

ar = np.empty((2,3),np.int8)

# print(ar)
print(np.eye(3,5,2))



[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
import numpy as np

print(np.identity(5,np.int64))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [16]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [20]:
print(np.linspace(0.1,15,15,False,True,int))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), np.float64(0.9933333333333334))
