In [1]:
import numpy as np

ar = np.full((2,2),5)
print(ar)

[[5 5]
 [5 5]]


In [5]:
import numpy as np
ar = np.random.rand(2,2)
print(ar)

[[0.05942092 0.49242337]
 [0.97750404 0.09883285]]


In [ ]:
import numpy as np

a = ['A','S']

ar = np.random.choice(a,(1,2),False,p=[0.4,0.6]

print(ar)

[['S' 'A']]


In [ ]:
import numpy as np

print(np.random.randint(1,2,5))


[1 1 1 1 1]


In [7]:
import numpy as np

a = [1,2,3,4,[5,6,7],8,9]

print(a[4][0])
print(a[4:5][:3])

5
[[5, 6, 7]]


In [8]:
import numpy as np

a = np.array([1,2,3,4])

print(a[1])

2


In [ ]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8]])

print(a[0:2,0:2])

[[1 2]
 [5 6]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])


In [11]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])

b = [1,4,5]
print(a[b])

[2 5 6]


In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[ 2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49 64 81]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0 0]
