In [ ]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8]])

print(a.flatten(order='k'))

# k = arange them in the sequence of there menmmmory address
# c = arnge in row wise 
# f = arange in coloumn wise

# return coppy 
# consumne memmory
# slower
# orginal array not will change if we change in coppy 


[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8]])

print(np.ravel(a))

# return view
# consumes less memory
# faster
# original will be change if we change in view 

[1 2 3 4 5 6 7 8]


In [10]:
import numpy as np

a = np.array([[[[1,2,3,4],
              [5,6,7,8]]]])

for i in np.nditer(a):
    print(i)
print(a.ndim)

1
2
3
4
5
6
7
8
4


In [11]:
import numpy as np

a = np.array([[[[1,2,3,4],
              [5,6,7,8]]]])

for i in np.ndenumerate(a):
    print(i)

((0, 0, 0, 0), np.int64(1))
((0, 0, 0, 1), np.int64(2))
((0, 0, 0, 2), np.int64(3))
((0, 0, 0, 3), np.int64(4))
((0, 0, 1, 0), np.int64(5))
((0, 0, 1, 1), np.int64(6))
((0, 0, 1, 2), np.int64(7))
((0, 0, 1, 3), np.int64(8))


In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])

print(np.split(a,4))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,],
             [5,6,7,8]])

print(np.split(a,2))

In [62]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7],
             [10,11,12,13,14,15,16]])

print(np.array_split(a, 2, axis=1))

[array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]]), array([[ 5,  6,  7],
       [14, 15, 16]])]


In [21]:
import numpy as np

a = np.array([[1,2,3,4],
             [5,6,7,8]])

print(np.transpose(a))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [29]:
import numpy as np

a = np.array([[8,7,6,5,4,3,2,1],
              [8,7,6,5,4,3,2,1]])

print(b := np.sort(a,axis=-1,kind='heapsort'))

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [30]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [32]:
b[::,::-1]

array([[8, 7, 6, 5, 4, 3, 2, 1],
       [8, 7, 6, 5, 4, 3, 2, 1]])

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,7])

print(np.where(a%2==0,0,a))
print(np.where(a%2==0))



a = np.array([[1,2,3,4,5],
              [8,9,10,11,12]])

print(np.where(a%2==0,0,a))
print(np.where(a%2==0))

[[ 1  0  3  0  5]
 [ 0  9  0 11  0]]
(array([0, 0, 1, 1, 1]), array([1, 3, 0, 2, 4]))


In [43]:
import numpy as np

a = np.array([1,2,3,4,5,7])

print(np.delete(a,[1,3]))

[1 3 5 7]


In [50]:
import numpy as np

a = np.array([[1,2,3],
             [4,5,6,],
             [7,8,9]])

# print(np.delete(a,1,axis=1))
print(np.delete(a,np.where(a%3==0)))

[4 5 6 7 8 9]


In [51]:
print(np.where(a % 3 == 0))

(array([0, 1, 2]), array([2, 2, 2]))


In [55]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,4,5,7])

print(np.intersect1d(a,b,assume_unique=True,return_indices=True))

(array([2, 4]), array([1, 3]), array([0, 1]))


In [59]:
import numpy as np
from functools import reduce


a = np.array([1,2,3,4])
b = np.array([2,4,5,7])
c = np.array([8,9,5,7])

print(reduce(np.union1d,(a,b,c)))

[1 2 3 4 5 7 8 9]
