In [8]:
import numpy as np

a = [1,2,3,4,5,6,7,8]

# print(np.reshape(a,(2,4)))
# print(np.reshape(a,(4,-1)))
print(np.reshape(a,(-1,2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])

print(np.concatenate((a, b), axis=1))

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [20]:
import numpy as np

# a = np.array([1,2,3,4,0,0,0,0,0,])
a = np.array([[1,2,0,4],[5,0,7,0]])

print(np.count_nonzero(a))

5


In [25]:
import numpy as np

# a = np.array([1,2,3,4,0,0,0,0,0,])
a = np.array([[1,2,0,4],[5,0,7,0]])

print(np.unique(a).size)
print(np.unique_counts(a))

6
UniqueCountsResult(values=array([0, 1, 2, 4, 5, 7]), counts=array([3, 1, 1, 1, 1, 1]))


In [ ]:
import numpy as np

a = np.array([0,0,0,0,0,1,2,3,0,0,4,0,5,0,6,0,0,0,0,0])

print(np.trim_zeros(a,trim='b'))
print(np.trim_zeros(a,trim='fb'))
print(np.trim_zeros(a,trim='f'))

[0 0 0 0 0 1 2 3 0 0 4 0 5 0 6]


In [32]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.copy(a)
c = a.view()

np.delete(b,4)
np.delete(c,4)

print(a)
print(b)
print(c)


[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [36]:
import numpy as np

a = np.array([1,2,3,4,5,6])
a2 = np.array([6,7,8,9,10])

print(np.setxor1d(a,a2))
print(np.setdiff1d(a,a2))

[ 1  2  3  4  5  7  8  9 10]
[1 2 3 4 5]


In [37]:
import numpy as np

a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [41]:
import numpy as np

a = np.array([[1,2,13],
              [3,4,14],
              [11,12,15]])
b = np.array([[5,6,16],
              [7,8,17],
              [9,10,18]])

print(np.cross(a,b))

[[-46  49  -4]
 [-44  47  -4]
 [ 66 -63   2]]


In [45]:
import numpy as np

a = np.array([[1,2,3],
              [5,5,6]])
b = np.array([[4,5,6],
              [7,8,9]])

print(np.cross(a,b))

[[-3  6 -3]
 [-3 -3  5]]


In [46]:
a = np.array([1,2,3,4,5,6])
a2 = np.array([6,7,8,9,10])

print(a,a2)

[1 2 3 4 5 6] [ 6  7  8  9 10]


In [50]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))
print(np.power(a,b))
print(np.sqrt(a))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 6 14 24 36 50]
[      1     128    6561  262144 9765625]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [51]:
a = np.array([1,5,3,9,7])

print(np.var(a))

8.0


In [52]:
a = np.array([1,5,3,9,7])

print(np.std(a))

2.8284271247461903


In [62]:
a = np.array([1,5,3,9,7])

print(np.save("arr_txt.npy",a))
print(np.load("arr_txt.npy"))
print(np.savetxt("arr_txt2.txt",a))
print(np.loadtxt("arr_txt.txt",a))

None
[1 5 3 9 7]
None


TypeError: Cannot construct a dtype from an array