In [3]:
import numpy as np 

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np 

a = np.array([1,2,3,4,5,6,7,8,9,10])
print("shape :- " , a.shape)
print("dataType :- " , a.dtype)
print("No. of dimnetion :- " , a.ndim)

shape :-  (10,)
dataType :-  int64
No. of dimnetion :-  1


In [9]:
import numpy as np 

a = np.zeros((3,3))
print(a)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
import numpy as np

a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
import numpy as np

a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
import numpy as np

a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [17]:
import numpy as np

a = np.linspace(0,100,11)
print(a)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [18]:
import numpy as np

a = np.arange(1,13)
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
import numpy as np

a = np.arange(1,10)
print(a[0])

1


In [25]:
import numpy as np

a = np.arange(1,11)

# print(np.size(a))
print(a[9])

10


In [26]:
import numpy as np

a = np.arange(1,21)

print(a[5:11])

[ 6  7  8  9 10 11]


In [27]:
import numpy as np

a = np.arange(1,11)

print(a[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [31]:
import numpy as np

a = np.arange(1,11)

print(np.max(a))

10


In [32]:
import numpy as np

a = np.arange(1,11)

print(np.min(a))

1


In [33]:
import numpy as np

a = np.arange(1,11)

print(np.sum(a))

55


In [34]:
import numpy as np

a = np.arange(1,11)

print(np.mean(a))

5.5


In [35]:
import numpy as np

a = np.arange(1,11)

print(np.median(a))

5.5


In [36]:
import numpy as np

a = np.arange(1,11)

print(np.std(a))

2.8722813232690143


In [37]:
import numpy as np

a = np.arange(1,11)
b = np.arange(11,21)

print(a+b)

[12 14 16 18 20 22 24 26 28 30]


In [38]:
import numpy as np

a = np.arange(1,11)

print(a*b)

[ 11  24  39  56  75  96 119 144 171 200]


In [67]:
import numpy as np

a = np.arange(1,11)

print(a**2)

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
import numpy as np

a = np.arange(1,21)

print(a[np.where(a % 2 == 0)])
print(a[a % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


In [49]:
import numpy as np

a = np.array([10,25,60,75,30,90,45])

print(np.count_nonzero(a>50))

3


In [53]:
import numpy as np

a = np.array([[1,2,3],
               [4,5,6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a.sum(axis=1))

[ 6 15 24]


In [57]:
import numpy as np

a = np.arange(1,26)


print(a.reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np

a = np.arange(1,11)

print(np.where(a%3==0,-1,a))

[ 1  2 -1  4  5 -1  7  8 -1 10]


In [65]:
import numpy as np

a = np.random.randint(1,111,10)

print(a)

[ 48 109  69  15  66  39   4  49  75  68]


In [66]:
import numpy as np

a = np.random.randint(1,111,10)
print(a)

print(a.max())

[ 15  36  77  90  96  79  28 108  33  67]
108


In [ ]:
import numpy as np

a = np.ones((8,8))

for i in range(0,8):
    if i%2 == 0:
        a[i,::2] = 0
    else:
        a[i,1::2] = 0
        
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
