In [1]:
import numpy as np

a = np.zeros((8,8))

for i in range(0,8):
    if i%2 == 0:
        a[i,::2] = 1
    else:
        a[i,1::2] = 1
        
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [5]:
import numpy as np

a = np.ones((5,5))

a[1:4,1:4] = 0
        
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
import numpy as np

a = np.array([5,12,7,18,25,3,15])
        
print(np.where(a>10,-1,a))

[ 5 -1  7 -1 -1  3 -1]


In [10]:
import numpy as np

a = np.arange(1,100)
        
print(a[np.where(a%3==0)])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [11]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(np.intersect1d(a,b))

[4 5]


In [34]:
# import numpy as np

# a = np.array([1,2,4,5,6,7,9])

# for i in range(a.size - 1):
#     if a[i+1] - a[i] > 1:
#         print(a[i] + 1)

import numpy as np

a = np.array([1,2,4,5,6,7,9])

b = np.arange(a.min(), a.max()+1)

print(np.setdiff1d(b, a))

[3 8]


In [35]:
import numpy as np

a = np.array([[4,3,2],
             [9,1,5],
             [7,6,3]])

for i in range(3):
    print(np.max(a[i]))

4
9
7


In [53]:
import numpy as np

a = np.array([[4,3,2],
             [9,1,5],
             [7,6,3]])

for i in range(1,4):
    print(np.sum(a[:,i-1:i])) 

20
10
10


In [ ]:
# Q.9
import numpy as np

a = np.array([[4,3,2],
             [9,1,5],
             [7,6,3]])

In [56]:
import numpy as np

a = np.array([[4,3,2,6],
             [9,1,5,8],
             [7,6,3,0],
             [4,6,7,9]])

print(a.flatten())

[4 3 2 6 9 1 5 8 7 6 3 0 4 6 7 9]


In [58]:
import numpy as np

a = np.arange(1,25)

print(a.reshape(2,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
import numpy as np

a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
for i in a:
    print(i[::-1])

[3 2 1]
[6 5 4]
[9 8 7]


In [80]:
import numpy as np

a = np.array([10,5,20,15,8,3])

print(np.sort(a))

[ 3  5  8 10 15 20]


In [82]:
import numpy as np

a = np.array([[9,4,7],
             [2,8,1],
             [6,5,3]])

for i in range(3):
    print(np.sort(a[i]))

[4 7 9]
[1 2 8]
[3 5 6]


In [84]:
import numpy as np

a = np.array([11,22,35,40,55,60])

print(np.where(a%2==0))

(array([1, 3, 5]),)


In [85]:
import numpy as np

a = np.array([1,2,2,3,4,4,5,5,5])
print(np.unique(a))

[1 2 3 4 5]


In [87]:
import numpy as np

a = np.array([1,2,2,3,3,3,3,3,3,2,1,2,5,4,3,4,4,4,4,4,4])

print(np.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5]), array([2, 4, 7, 7, 1]))


In [88]:
import numpy as np

a = np.array([10,20,30,40,50])

norm_data = (a-a.min())/(a.mean()-a.min())

print(norm_data)

[0.  0.5 1.  1.5 2. ]


In [92]:
import numpy as np

a = np.random.randint(1,111,25)
print(a.reshape(5,5))

[[ 55  20  47  16  31]
 [ 64  78  12  58  33]
 [109  58  25  35  95]
 [ 76  15  13  17  58]
 [ 78  43  93  54  37]]


In [99]:
import numpy as np

a = np.array([10,50,20,80,60,90])

a.sort()

print(a[-2])

80


In [ ]:
import numpy as np

a = np.array([1,2,3,4,2,5,6,1,7])

v,c = np.unique(a,return_counts=True)

# print(v,c)

print(v[np.where(c>1)])

[1 2 3 4 5 6 7] [2 2 1 1 1 1 1]
[1 2]


In [105]:
import numpy as np

a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(np.diag(a).sum())
print(np.trace(a))

15
15


In [12]:
import numpy as np

a = np.array([1,2,3,4])

# print(a[np.newaxis,::])
# print(a[:,np.newaxis])

x = np.arange(1,11)
mt = x*x[:,np.newaxis]

import numpy as np

ar = np.empty((2,3),np.int8)

# print(ar)
print(np.eye(3,5,-1))



print()

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]

