In [48]:
import numpy as np

a = np.array([[[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]]])

print(a[0,1,2])
print(a[0,-1,-2])

7
11


In [45]:
import numpy as np

a = np.array([[1,2,3,4],
             [5,6,7,8]])

print(a[0,2])
print(a[-1,-2])

3
7


In [42]:
import numpy as np

a = np.array([1,2,3,4])

print(a[1])
print(a[-1])

2
4


In [39]:
import numpy as np

# randome intigers array b/w 1-50 in 2,4 format 
arr = np.random.randint(1, 51, 8)

print(arr.reshape(2,4))

[[25  8 15 14]
 [29 29 27 39]]


In [41]:
import numpy as np

# randome intigers array b/w 1-50 in 2,4 format 
arr = np.random.randint(1, 51, (2,4))
print(arr)

# print(arr.reshape(2,4))

[[33 48 23 14]
 [ 2 40 37  7]]


In [35]:
import numpy as np

arr = np.full((3,3),9)

print("each elementshoud be 9 :- ")
print(arr)

each elementshoud be 9 :- 
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [32]:
import numpy as np

print(np.linspace(0, 100, 10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [33]:
import numpy as np

arr = np.arange(2, 21, 2)

print("even number 1-20" , arr)

even number 1-20 [ 2  4  6  8 10 12 14 16 18 20]


In [30]:
import numpy as np

arr = np.arange(21)

print(arr)
print("shape of array :- " , arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
shape of array :-  (21,)


In [29]:
import numpy as np

arr = np.eye(5)

print(arr)
print("shape of array :- " , arr.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
shape of array :-  (5, 5)


In [28]:
import numpy as np

arr = np.ones((4,4))

print(arr)
print("shape of array :- " , arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape of array :-  (4, 4)


In [26]:
import numpy as np

arr = np.zeros((3,3))

print(arr)
print("shape of array :- " , arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape of array :-  (3, 3)


In [23]:
import numpy as np

arr = np.array([[1,2,3],
               [4,5,6]])

print("shape of array :- " , arr.shape)

shape of array :-  (2, 3)


In [19]:
import numpy as np

arr = np.array([1,2,3,4,5])

print("intigers array :- ",arr)
print("size of arry :- " , arr.size)
print("dimention of array :- " , arr.ndim)
print("shape of array :- " , arr.shape)
print("data type of array :- " , arr.dtype)
print("item size of array :- " , arr.itemsize)
print("Total size ocupies by array :- " , arr.nbytes)



intigers array :-  [1 2 3 4 5]
size of arry :-  5
dimention of array :-  1
shape of array :-  (5,)
data type of array :-  int64
item size of array :-  8
Total size ocupies by array :-  40


In [15]:
import numpy as np

x = np.full((2,2),0.9)

print(x)

[[0.9 0.9]
 [0.9 0.9]]


In [14]:
import numpy as np

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a.dtype)

b = a.astype(float)

print(b)
print(b.dtype)

In [13]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a.nbytes)

40


In [11]:
import numpy as np

x = np.arange(1,11)

print(x)
print(np.sum(x))


[ 1  2  3  4  5  6  7  8  9 10]
55


In [9]:
import numpy as np 

x = np.array([[1,2,3,4],
             [5,6,7,8]])

print(x.flatten())

[1 2 3 4 5 6 7 8]


In [7]:
import numpy as np

x = np.array([1,2,3,4])

print(x)

print(x.reshape(2,2))

[1 2 3 4]
[[1 2]
 [3 4]]


In [6]:
import numpy as np 

x = np.array([1,2,3,4])

print(x.dtype)

int64


In [5]:
import numpy as np

x = np.array([[1,2,3,4],
             [5,6,7,8]])

print(x.size)

8


In [4]:
import numpy as np

x = np.array([[1,2,3,4],
             [5,6,7,8]])

print(x.ndim)

2


In [3]:
import numpy as np

print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np

print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [1]:
import numpy as np

print(np.linspace(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
