In [20]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[-2:-1,-3:-1:])

[[40 50]]


In [26]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[1:2,0:3])

[[40 50 60]]


In [32]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[2:,1:2])
print(a[2,1])

[[80]]
80


In [ ]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[0:,0:1])

[[10]
 [40]
 [70]]


In [37]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[1:,1:])
print(a[-2:,-2:])

[[50 60]
 [80 90]]
[[50 60]
 [80 90]]


In [40]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[-3:,-2:])

[[20 30]
 [50 60]
 [80 90]]


In [43]:
import numpy as np

a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90,]])

print(a[1:, :2][::-1, ::-1])

[[80 70]
 [50 40]]


In [66]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])

print(a[1:4,1:4])

print(a[-4:-1,-4:-1])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [67]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])

print(a[-4:-2,-5:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [71]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])

print(a[-3:-5:-1,-5:])

[[11 12 13 14 15]
 [ 6  7  8  9 10]]
